import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat, Hind_Siliguri } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import MenuSection from "@/components/MenuSection";


const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["300","400","500","600","700"],
  variable: "--font-montserrat"
});
const hindSiliguri = Hind_Siliguri({
  subsets: ["bengali"],
  variable: "--font-bengali",
  weight: ["400","500","600","700"]
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${montserrat.variable} ${hindSiliguri.variable} h-full antialiased text-[#000000]`}
    >
      <body suppressHydrationWarning className="min-h-full flex flex-col mt-[36px] xl:mt-[55px]">
        <Navbar />
        {children}
        <MenuSection />
      </body>
    </html>
  );
}
